### ISSUE TITLE
Missing Exports Condition Warning in Sveltekit

### ISSUE THREAD

**Issue by ccalobeto** [ONSvisual/svelte-maps#4]
Using this library in Sveltekit is showing a missing exports condition warning:

> The following packages have a svelte field in their package.json but no exports condition for svelte.
@onsvisual/svelte-maps@1.2.19
Please see https://github.com/sveltejs/vite-plugin-svelte/blob/main/docs/faq.md#missing-exports-condition for details

and the link 
> If you see a warning logged for this when using a Svelte library, please tell the library maintainers.

Using the svelte field in package.json to point at .svelte source files is deprecated and you must use a svelte [export condition](https://nodejs.org/api/packages.html#conditional-exports). vite-plugin-svelte 3 still resolves it as a fallback, but in a future major release this is going to be removed and without exports condition resolving the library is going to fail.

Example 

package.json
> "files": ["dist"],
 "svelte": "dist/index.js",
`+ "exports": {`
`+   ".": {`
`+     "svelte": "./dist/index.js"`
`+   }`
  }

**Comment by henryjameslau** [comment]
Hi @ccalobeto, hopefully this is now fixed with https://github.com/ONSvisual/svelte-maps/commit/3cd0b0fe24b4be37f39a9bcae5b3380d976a30d3. Thanks for you input. Henry
